services:
  ham-api:
    image: wiremock/wiremock:3.13.2-2-alpine
    ports:
      - "9000:8080"
    volumes:
      - ./src/test/resources/wiremock:/home/wiremock
  flights-redis:
    image: redis:8.4.0-alpine3.22
    ports:
      - "6379:6379"